export default {
    PADECIMIENTOS_CARGAR_INICIO: "PADECIMIENTOS_CARGAR_INICIO",
    PADECIMIENTOS_CARGAR_CORRECTAMENTE: "PADECIMIENTOS_CARGAR_CORRECTAMENTE",
    PADECIMIENTOS_CARGAR_ERROR: "PADECIMIENTOS_CARGAR_ERROR",
}